### ISSUE TITLE
Dark theme problem

### ISSUE THREAD

**Issue by Arubinu** [cube-creative/guibedos#1]
Hello,

I'm on OSX and use PyQt5, almost everything works fine.
The problem is that dark themes do not work on all elements.
The background and checkboxes do not take the style and stay in the light theme...

I just discovered this tool, but it looks very interesting!
Thank you very much :)

**Comment by Arubinu** [comment]
Using the following code after declaring the widget, the problem is solved:
```
p = widget.palette()
p.setColor( widget.backgroundRole(), QtGui.QColor( 110, 110, 110 ) )
widget.setPalette( p )
```

Think about importing QtGui:
```
from Qt import QtWidgets, QtGui
```

**Comment by developer-cube-creative** [comment]
Hi, 

Thanks for your input !

This issue is know, FreeCAD stylesheets are designed to work on applications using QMainWindow and QDialog
stylesheets might be updated to also color QWidgets, but it might interfere with other widgets...

All the best
